package com.golden.core;

import com.golden.config.StaticConfig;
import com.golden.util.FormatHelper;

import java.util.Scanner;

public class Ui {

    public Ui(){ }

    private String getBotName(){
        return StaticConfig.APP_NAME;
    }

    public void greet() {
        FormatHelper.printFormattedReply(String.format(
                "Hello! I'm  %s.\nWhat can I do for you?", getBotName()));
    }

    /**
     * Returns the raw input line collected from the UI.
     * @return the String input typed into the UI delimited by a line break or new line.
     */
    public String readCommand() {
        Scanner input = new Scanner(System.in);
        return input.nextLine();
    }

    /**
     * Prints a formatted error message.
     *
     * @param errorMsg The error message generated by the program.
     *
     * @return the formatted output of the error message given.
     */
    public void showError(String errorMsg){
        FormatHelper.printFormattedReply(errorMsg);
    }


    /**
     * Prints a formatted reply.
     *
     * @param replyString The reply generated by the program.
     *
     * @return the formatted output of the reply string given.
     */
    public void printBotReply(String replyString){
        FormatHelper.printFormattedReply(replyString);
    }
}